version: "3.1"
services:
  opengl-webassembly:
    build: .
    image: julie.com/opengl-webassembly:latest
    volumes:
      - ..:/opt/code/
      - ../cache/:/root/.emscripten_cache/
    ports:
      - 8085:8085
    entrypoint:
      - /bin/bash
      - -c
      - ./docker/launch.sh
